# Generated by Django 3.1.5 on 2021-01-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('prog_language', models.CharField(max_length=8)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('submissions', models.FileField(upload_to='./')),
            ],
        ),
    ]
