# Generated by Django 3.1.5 on 2021-01-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jplag_catcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='prog_language',
            field=models.CharField(choices=[('java19', 'Java 1.9'), ('java17', 'Java 1.7'), ('java15', 'Java 1.5'), ('java15dm', 'Java 1.5 DM'), ('java12', 'Java 1.2'), ('java11', 'Java 1.1'), ('python3', 'Python 3'), ('c/c++', 'C/C++'), ('c#-1.2', 'C# 1.2'), ('char', 'Char'), ('text', 'Text'), ('scheme', 'Scheme')], max_length=8),
        ),
    ]
